### ISSUE TITLE
Trouble with creating an env file

### ISSUE THREAD

**Issue by svgandhi** [edleeman17/omnivore-opml-import#5]
I am trying to import inoreader feeds into omnivore.  I have duplicated the repository on my Mac and added my xml file to the import directory. But I don’t know how to create an env file or where it should be located.  Can someone tell me how?

**Comment by edleeman17** [comment]
Hey!

In the repository you'll find a '.env.sample' file. You can actually rename this to '.env'. Be sure to leave it where it is as it's exactly where it needs to be.

Open up the '.env' file and enter your API key. 

Let me know if you need any help!

**Comment by svgandhi** [comment]
Actually there are a few files missing from my repository that appear on the project page.  I don’t see .env.sample.  I have tried using the url and the zip file to clone the repository.

**Comment by edleeman17** [comment]
Hey,

The files may be hidden, try this:

https://discussions.apple.com/thread/7581737

**Comment by svgandhi** [comment]
How do I perform steps four and five in Installation and Usage?

**Comment by svgandhi** [comment]
I installed Docker then entered the command from step 4 while in terminal ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory.

**Comment by edleeman17** [comment]
Are you running the command from inside the directory which contains the Dockerfile?

**Comment by svgandhi** [comment]
I figured it out.  I realized I had to download the Docker app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
